
CREATE TABLE IF NOT EXISTS FeedingOperation();
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS areaServed Geometry(Polygon, 4326);
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS ngsildTenant text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS ngsildPath text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS ngsildContext text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS ngsildData jsonb;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS address jsonb;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS alternateName text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS category jsonb;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS dataProvider text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS dateCreated text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS dateModified text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS endpoint text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS hasProvider text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS owner jsonb;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS relatedSource jsonb;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS seeAlso text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE FeedingOperation ADD COLUMN IF NOT EXISTS version text;

CREATE TABLE IF NOT EXISTS Feeder();
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS areaServed Geometry(Polygon, 4326);
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS ngsildTenant text;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS ngsildPath text;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS ngsildContext text;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS ngsildData jsonb;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS address jsonb;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS alternateName text;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS dataProvider text;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS dateCreated text;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS dateModified text;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS owner jsonb;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS relatedSource jsonb;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS seeAlso text;
ALTER TABLE Feeder ADD COLUMN IF NOT EXISTS source text;

CREATE TABLE IF NOT EXISTS Feed();
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS areaServed Geometry(Polygon, 4326);
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS ngsildTenant text;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS ngsildPath text;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS ngsildContext text;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS ngsildData jsonb;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS address jsonb;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS alternateName text;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS dataProvider text;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS dateCreated text;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS dateModified text;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS owner jsonb;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS relatedSource jsonb;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS seeAlso text;
ALTER TABLE Feed ADD COLUMN IF NOT EXISTS source text;

CREATE TABLE IF NOT EXISTS SiteUser();
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userId text UNIQUE;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userEmail text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFirstName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userLastName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFullName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS seeArchived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS displayName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS siteFontSize text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS siteTheme text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS webComponentsTheme text;

CREATE TABLE IF NOT EXISTS MapModel();
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS areaServed Geometry(Polygon, 4326);
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS ngsildTenant text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS ngsildPath text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS ngsildContext text;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS ngsildData jsonb;
ALTER TABLE MapModel ADD COLUMN IF NOT EXISTS color text;

CREATE TABLE IF NOT EXISTS FishPopulation();
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS areaServed Geometry(Polygon, 4326);
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS ngsildTenant text;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS ngsildPath text;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS ngsildContext text;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS ngsildData jsonb;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS color text;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS address jsonb;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS alternateName text;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS bodyMasse decimal;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS culturedIn decimal;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS dataProvider text;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS dateCreated text;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS dateModified text;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS fishRemoved decimal;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS initialNumber decimal;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS owner jsonb;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS refSpecie decimal;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS relatedSource jsonb;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS seeAlso text;
ALTER TABLE FishPopulation ADD COLUMN IF NOT EXISTS source text;

CREATE TABLE IF NOT EXISTS FishFarm();
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS areaServed Geometry(Polygon, 4326);
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS ngsildTenant text;
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS ngsildPath text;
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS ngsildContext text;
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS ngsildData jsonb;
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS color text;
ALTER TABLE FishFarm ADD COLUMN IF NOT EXISTS address jsonb;

CREATE TABLE IF NOT EXISTS FishingDock();
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS areaServed Geometry(Polygon, 4326);
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS ngsildTenant text;
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS ngsildPath text;
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS ngsildContext text;
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS ngsildData jsonb;
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS color text;
ALTER TABLE FishingDock ADD COLUMN IF NOT EXISTS address jsonb;

CREATE TABLE IF NOT EXISTS FishProcessing();
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS areaServed Geometry(Polygon, 4326);
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS ngsildTenant text;
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS ngsildPath text;
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS ngsildContext text;
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS ngsildData jsonb;
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS color text;
ALTER TABLE FishProcessing ADD COLUMN IF NOT EXISTS address jsonb;

CREATE TABLE IF NOT EXISTS FishingTrip();
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS userKey bigint;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS objectTitle text;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS displayPage text;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS location point;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS areaServed Geometry(Polygon, 4326);
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS id text;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS ngsildTenant text;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS ngsildPath text;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS ngsildContext text;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS ngsildData jsonb;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS color text;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS timeZone text;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS departureDate timestamp with time zone;
ALTER TABLE FishingTrip ADD COLUMN IF NOT EXISTS arrivalDate timestamp with time zone;
