DROP TABLE CrowdFlowObserved CASCADE;
DROP TABLE FeedingOperation CASCADE;
DROP TABLE FishPopulation CASCADE;
DROP TABLE Feeder CASCADE;
DROP TABLE Feed CASCADE;
DROP TABLE SiteUser CASCADE;
DROP TABLE FishingTrip CASCADE;
