DROP TABLE Feed CASCADE;
DROP TABLE Feeder CASCADE;
DROP TABLE SiteUser CASCADE;
DROP TABLE FishPopulation CASCADE;
DROP TABLE FeedingOperation CASCADE;
DROP TABLE FishingTrip CASCADE;
DROP TABLE FishingDock CASCADE;
DROP TABLE FishFarm CASCADE;
