apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: smartaquaculture
  namespace: smartaquaculture
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
